In [23]:
import os
import json
import pandas as pd
from typing import Dict, List

In [24]:
pd.set_option('display.max_columns', None)

In [25]:
DATA_DIR = '/Users/meetpatel/Desktop/dm-project/machine-failure-prediction/csv'
SAVE_DATA_DIR = os.path.join(DATA_DIR, 'targets_data/')
PREPROCESSED_DATA_F = 'preprocessed_data_variable_hour_window_cols.csv'
PREPROCESSED_DATA_LOC = os.path.join(DATA_DIR, PREPROCESSED_DATA_F)

In [26]:
df = pd.read_csv(
    PREPROCESSED_DATA_LOC,
)
print(f"- {format(len(df), ',')} total rows in df.")
df.head(3)

- 876,100 total rows in df.

,datetime,machineID,volt,rotate,pressure,vibration,12_machineID_time_window,12_order_in_time_window,12_machine_example_ID,12_step_ID,24_machineID_time_window,24_order_in_time_window,24_machine_example_ID,24_step_ID,48_machineID_time_window,48_order_in_time_window,48_machine_example_ID,48_step_ID,72_machineID_time_window,72_order_in_time_window,72_machine_example_ID,72_step_ID,comp1_maint,comp2_maint,comp3_maint,comp4_maint,error1,error2,error3,error4,error5,comp1_failure,comp2_failure,comp3_failure,comp4_failure,age,model2,model3,model4
0,2015-01-01 06:00:00,1,176.217853,418.504078,113.077935,45.087686,1,1,"(001, 001)","(001, 001, 001)",1,1,"(001, 001)","(001, 001, 001)",1,1,"(001, 001)","(001, 001, 001)",1,1,"(001, 001)","(001, 001, 001)",0,0,0,0,0,0,0,0,0,0,0,0,0,18,False,True,False
1,2015-01-01 07:00:00,1,162.879223,402.747490,95.460525,43.413973,1,2,"(001, 001)","(001, 001, 002)",1,2,"(001, 001)","(001, 001, 002)",1,2,"(001, 001)","(001, 001, 002)",1,2,"(001, 001)","(001, 001, 002)",0,0,0,0,0,0,0,0,0,0,0,0,0,18,False,True,False
2,2015-01-01 08:00:00,1,170.989902,527.349825,75.237905,34.178847,1,3,"(001, 001)","(001, 001, 003)",1,3,"(001, 001)","(001, 001, 003)",1,3,"(001, 001)","(001, 001, 003)",1,3,"(001, 001)","(001, 001, 003)",0,0,0,0,0,0,0,0,0,0,0,0,0,18,False,True,False

In [27]:
df = df[
    [
        'datetime', 'machineID',
        '12_machineID_time_window', '12_order_in_time_window', '12_machine_example_ID', '12_step_ID',
        '24_machineID_time_window', '24_order_in_time_window', '24_machine_example_ID', '24_step_ID',
        '48_machineID_time_window', '48_order_in_time_window', '48_machine_example_ID', '48_step_ID',
        '72_machineID_time_window', '72_order_in_time_window', '72_machine_example_ID', '72_step_ID',
        'age',
        'model2', 'model3', 'model4',
        'volt', 'rotate', 'pressure', 'vibration',
        'comp1_maint', 'comp2_maint', 'comp3_maint', 'comp4_maint',
        'error1', 'error2', 'error3', 'error4', 'error5',
        'comp1_failure', 'comp2_failure', 'comp3_failure', 'comp4_failure',
    ]
]

In [28]:
df['datetime'] = pd.to_datetime(df['datetime'])
df['machineID'] = df['machineID'].astype(int)

df['12_machineID_time_window'] = df['12_machineID_time_window'].astype(int)
df['12_order_in_time_window'] = df['12_order_in_time_window'].astype(int)
df['12_machine_example_ID'] = df['12_machine_example_ID'].astype(str)
df['12_step_ID'] = df['12_step_ID'].astype(str)
df['24_machineID_time_window'] = df['24_machineID_time_window'].astype(int)
df['24_order_in_time_window'] = df['24_order_in_time_window'].astype(int)
df['24_machine_example_ID'] = df['24_machine_example_ID'].astype(str)
df['24_step_ID'] = df['24_step_ID'].astype(str)
df['48_machineID_time_window'] = df['48_machineID_time_window'].astype(int)
df['48_order_in_time_window'] = df['48_order_in_time_window'].astype(int)
df['48_machine_example_ID'] = df['48_machine_example_ID'].astype(str)
df['48_step_ID'] = df['48_step_ID'].astype(str)
df['72_machineID_time_window'] = df['72_machineID_time_window'].astype(int)
df['72_order_in_time_window'] = df['72_order_in_time_window'].astype(int)
df['72_machine_example_ID'] = df['72_machine_example_ID'].astype(str)
df['72_step_ID'] = df['72_step_ID'].astype(str)

df['age'] = df['age'].astype(int)
df['model2'] = df['model2'].astype(int)
df['model3'] = df['model3'].astype(int)
df['model4'] = df['model4'].astype(int)

df['volt'] = df['volt'].astype(float)
df['rotate'] = df['rotate'].astype(float)
df['pressure'] = df['pressure'].astype(float)
df['vibration'] = df['vibration'].astype(float)
df['comp1_maint'] = df['comp1_maint'].astype(int)
df['comp2_maint'] = df['comp2_maint'].astype(int)
df['comp3_maint'] = df['comp3_maint'].astype(int)
df['comp4_maint'] = df['comp4_maint'].astype(int)
df['error1'] = df['error1'].astype(int)
df['error2'] = df['error2'].astype(int)
df['error3'] = df['error3'].astype(int)
df['error4'] = df['error4'].astype(int)
df['error5'] = df['error5'].astype(int)
df['comp1_failure'] = df['comp1_failure'].astype(int)
df['comp2_failure'] = df['comp2_failure'].astype(int)
df['comp3_failure'] = df['comp3_failure'].astype(int)
df['comp4_failure'] = df['comp4_failure'].astype(int)

In [29]:
df.head(3)

,datetime,machineID,12_machineID_time_window,12_order_in_time_window,12_machine_example_ID,12_step_ID,24_machineID_time_window,24_order_in_time_window,24_machine_example_ID,24_step_ID,48_machineID_time_window,48_order_in_time_window,48_machine_example_ID,48_step_ID,72_machineID_time_window,72_order_in_time_window,72_machine_example_ID,72_step_ID,age,model2,model3,model4,volt,rotate,pressure,vibration,comp1_maint,comp2_maint,comp3_maint,comp4_maint,error1,error2,error3,error4,error5,comp1_failure,comp2_failure,comp3_failure,comp4_failure
0,2015-01-01 06:00:00,1,1,1,"(001, 001)","(001, 001, 001)",1,1,"(001, 001)","(001, 001, 001)",1,1,"(001, 001)","(001, 001, 001)",1,1,"(001, 001)","(001, 001, 001)",18,0,1,0,176.217853,418.504078,113.077935,45.087686,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2015-01-01 07:00:00,1,1,2,"(001, 001)","(001, 001, 002)",1,2,"(001, 001)","(001, 001, 002)",1,2,"(001, 001)","(001, 001, 002)",1,2,"(001, 001)","(001, 001, 002)",18,0,1,0,162.879223,402.747490,95.460525,43.413973,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2015-01-01 08:00:00,1,1,3,"(001, 001)","(001, 001, 003)",1,3,"(001, 001)","(001, 001, 003)",1,3,"(001, 001)","(001, 001, 003)",1,3,"(001, 001)","(001, 001, 003)",18,0,1,0,170.989902,527.349825,75.237905,34.178847,0,0,0,0,0,0,0,0,0,0,0,0,0

### 1. Define Helper Function to Obtain Outcomes

In [30]:
def identify_future_failures_dict(
    df: pd.DataFrame,
    machine_example_id_col: str,
    hours_ahead: int = 168,
) -> Dict[str, int]:
    """
    Purpose: Creates dictionary indicating if any failure occurs within a
        specified number of hours for each machine_example_ID.
    :param df: DataFrame containing machine data.
    :param hours_ahead: int representing the number of hours to look ahead for
        failures from the max datetime of each machine_example_ID.
    :return: Dict with 'machine_example_ID' as keys and binary values indicating
        future failures.
    """
    printed_machineIDs_set = set()

    # grouping by 'machine_example_ID' and findind the max DTM for each group;
    # max DTM for each group should be 23:00
    max_datetime_per_id = df.groupby(machine_example_id_col)['datetime'].max()

    # obtain dict by iterating through each unique machine_example_ID
    future_failures_dict = dict()
    for machine_example_id, max_datetime in max_datetime_per_id.items():

        # calculate window for the specified number of hours after the max DTM
        window_start = max_datetime + pd.Timedelta(hours = 1)
        window_end = max_datetime + pd.Timedelta(hours = hours_ahead)

        # get machineID
        machineID = int(machine_example_id[1:4])

        if machineID not in printed_machineIDs_set:
            print(machineID, end="   ")
            printed_machineIDs_set.add(machineID)

        filtered_df = df[
            # filter for machineID
            (df['machineID'] == machineID)

            # filter for rows within "look-ahead" window
            & (window_start <= df['datetime'])
            & (df['datetime'] <= window_end)

            # filter for rows with any failure
            & (
                (df['comp1_failure'] == 1)
                | (df['comp2_failure'] == 1)
                | (df['comp3_failure'] == 1)
                | (df['comp4_failure'] == 1)
            )
        ]

        # update dict for this machine_example_ID
        if len(filtered_df) > 0:
            future_failures_dict[machine_example_id] = 1
        else:
            future_failures_dict[machine_example_id] = 0

    return future_failures_dict

### 2. Create Targets Data Dicts From Preprocessed Data

In [31]:
for hour_feature_window in [12, 24, 48, 72]:
    print(f"- Hour Feature Window: {hour_feature_window}")

    for hour_lookahead in [1, 6, 24, 96, 168]:
        print(f"\t- Hours Lookahead: {hour_lookahead}")

        targets_dict = identify_future_failures_dict(
            df = df,
            machine_example_id_col = f'{hour_feature_window}_machine_example_ID',
            hours_ahead = hour_lookahead
        )

        prevalence = sum(v == 1 for v in targets_dict.values()) / len(targets_dict)
        print(f"\t\t- {format(len(targets_dict), ',')} total key-value pairs in targets_dict.")
        print(f"\t\t\t- Prevalence: {round(100 * prevalence, 2)}%.")

        # remove max order in time window key (there is no subsequent outcome on which to judge its outcome)
        max_order_in_time_window = df[f'{hour_feature_window}_order_in_time_window'].max()
        targets_dict = {
            k: v for k, v in targets_dict.items()
            if int(k[6:9]) != max_order_in_time_window
        }
        prevalence = sum(v == 1 for v in targets_dict.values()) / len(targets_dict)
        print(f"\t\t- {format(len(targets_dict), ',')} total key-value pairs in targets_dict.")
        print(f"\t\t\t- Prevalence: {round(100 * prevalence, 2)}%.")

        # save as JSON
        SAVE_FILENAME = f'targets_dict_anyfailure_{hour_feature_window}hrfeaturewindow_{hour_lookahead}hrlookahead.json'
        SAVE_LOC = os.path.join(SAVE_DATA_DIR, SAVE_FILENAME)
        with open(SAVE_LOC, mode = 'w') as json_f:
          json.dump(obj = targets_dict, fp = json_f, indent = 4)
        print(f"\t\t*Saved file: {SAVE_FILENAME}")

- Hour Feature Window: 12
	- Hours Lookahead: 1
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   		- 73,100 total key-value pairs in targets_dict.
			- Prevalence: 0.96%.
		- 73,000 total key-value pairs in targets_dict.
			- Prevalence: 0.96%.
		*Saved file: targets_dict_anyfailure_12hrfeaturewindow_1hrlookahead.json
	- Hours Lookahead: 6
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   		- 73,100 total key-value pairs in targets_dict.
			- Prevalence: 0.96%.
		- 73,000 total key-value pairs in targets_dict.
			- Prevalence: 0.96%.
		*Saved file: targets_dict_anyfailure_12hrfeaturewindow_6hrlookahead.json
	- Hours Lookahead: 24
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   		- 73,100 total key-value pairs in targets_dict.
			- Prevalence: 1.94%.
		- 73,000 total key-value pairs in targets_dict.
			- Prevalence: 1.94%.
		*Saved file: targets_dict_anyfailure_12hrfeaturewindow_24hrlookahead.json
	- Hours Lookahead: 96
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   		- 73,100 total key-value pairs in targets_dict.
			- Prevalence: 7.67%.
		- 73,000 total key-value pairs in targets_dict.
			- Prevalence: 7.67%.
		*Saved file: targets_dict_anyfailure_12hrfeaturewindow_96hrlookahead.json
	- Hours Lookahead: 168
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   		- 73,100 total key-value pairs in targets_dict.
			- Prevalence: 13.33%.
		- 73,000 total key-value pairs in targets_dict.
			- Prevalence: 13.33%.
		*Saved file: targets_dict_anyfailure_12hrfeaturewindow_168hrlookahead.json
- Hour Feature Window: 24
	- Hours Lookahead: 1
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   		- 36,600 total key-value pairs in targets_dict.
			- Prevalence: 1.92%.
		- 36,500 total key-value pairs in targets_dict.
			- Prevalence: 1.92%.
		*Saved file: targets_dict_anyfailure_24hrfeaturewindow_1hrlookahead.json
	- Hours Lookahead: 6
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   		- 36,600 total key-value pairs in targets_dict.
			- Prevalence: 1.92%.
		- 36,500 total key-value pairs in targets_dict.
			- Prevalence: 1.92%.
		*Saved file: targets_dict_anyfailure_24hrfeaturewindow_6hrlookahead.json
	- Hours Lookahead: 24
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   		- 36,600 total key-value pairs in targets_dict.
			- Prevalence: 1.92%.
		- 36,500 total key-value pairs in targets_dict.
			- Prevalence: 1.92%.
		*Saved file: targets_dict_anyfailure_24hrfeaturewindow_24hrlookahead.json
	- Hours Lookahead: 96
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   		- 36,600 total key-value pairs in targets_dict.
			- Prevalence: 7.64%.
		- 36,500 total key-value pairs in targets_dict.
			- Prevalence: 7.64%.
		*Saved file: targets_dict_anyfailure_24hrfeaturewindow_96hrlookahead.json
	- Hours Lookahead: 168
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   		- 36,600 total key-value pairs in targets_dict.
			- Prevalence: 13.29%.
		- 36,500 total key-value pairs in targets_dict.
			- Prevalence: 13.29%.
		*Saved file: targets_dict_anyfailure_24hrfeaturewindow_168hrlookahead.json
- Hour Feature Window: 48
	- Hours Lookahead: 1
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   		- 18,300 total key-value pairs in targets_dict.
			- Prevalence: 1.94%.
		- 18,200 total key-value pairs in targets_dict.
			- Prevalence: 1.94%.
		*Saved file: targets_dict_anyfailure_48hrfeaturewindow_1hrlookahead.json
	- Hours Lookahead: 6
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   		- 18,300 total key-value pairs in targets_dict.
			- Prevalence: 1.94%.
		- 18,200 total key-value pairs in targets_dict.
			- Prevalence: 1.94%.
		*Saved file: targets_dict_anyfailure_48hrfeaturewindow_6hrlookahead.json
	- Hours Lookahead: 24
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   		- 18,300 total key-value pairs in targets_dict.
			- Prevalence: 1.94%.
		- 18,200 total key-value pairs in targets_dict.
			- Prevalence: 1.94%.
		*Saved file: targets_dict_anyfailure_48hrfeaturewindow_24hrlookahead.json
	- Hours Lookahead: 96
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   		- 18,300 total key-value pairs in targets_dict.
			- Prevalence: 7.62%.
		- 18,200 total key-value pairs in targets_dict.
			- Prevalence: 7.63%.
		*Saved file: targets_dict_anyfailure_48hrfeaturewindow_96hrlookahead.json
	- Hours Lookahead: 168
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   		- 18,300 total key-value pairs in targets_dict.
			- Prevalence: 13.29%.
		- 18,200 total key-value pairs in targets_dict.
			- Prevalence: 13.32%.
		*Saved file: targets_dict_anyfailure_48hrfeaturewindow_168hrlookahead.json
- Hour Feature Window: 72
	- Hours Lookahead: 1
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   		- 12,200 total key-value pairs in targets_dict.
			- Prevalence: 2.07%.
		- 12,100 total key-value pairs in targets_dict.
			- Prevalence: 2.08%.
		*Saved file: targets_dict_anyfailure_72hrfeaturewindow_1hrlookahead.json
	- Hours Lookahead: 6
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   		- 12,200 total key-value pairs in targets_dict.
			- Prevalence: 2.07%.
		- 12,100 total key-value pairs in targets_dict.
			- Prevalence: 2.08%.
		*Saved file: targets_dict_anyfailure_72hrfeaturewindow_6hrlookahead.json
	- Hours Lookahead: 24
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   		- 12,200 total key-value pairs in targets_dict.
			- Prevalence: 2.07%.
		- 12,100 total key-value pairs in targets_dict.
			- Prevalence: 2.08%.
		*Saved file: targets_dict_anyfailure_72hrfeaturewindow_24hrlookahead.json
	- Hours Lookahead: 96
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   		- 12,200 total key-value pairs in targets_dict.
			- Prevalence: 7.78%.
		- 12,100 total key-value pairs in targets_dict.
			- Prevalence: 7.8%.
		*Saved file: targets_dict_anyfailure_72hrfeaturewindow_96hrlookahead.json
	- Hours Lookahead: 168
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   		- 12,200 total key-value pairs in targets_dict.
			- Prevalence: 13.41%.
		- 12,100 total key-value pairs in targets_dict.
			- Prevalence: 13.45%.
		*Saved file: targets_dict_anyfailure_72hrfeaturewindow_168hrlookahead.json

In [32]:
for hour_feature_window in [12, 24, 48, 72]:
    print(f"- Hour Feature Window: {hour_feature_window}")

    for hour_lookahead in [1, 6, 24, 72, 168]:

        # skip if already done
        if hour_feature_window == 12:
            if hour_lookahead in [1, 6, 24, 168]:
                print(f"*Skipping (hour_feature_window, hour_lookahead) = ({hour_feature_window}, {hour_lookahead})")
                continue


        print(f"\t- Hours Lookahead: {hour_lookahead}")

        targets_dict = identify_future_failures_dict(
            df = df,
            machine_example_id_col = f'{hour_feature_window}_machine_example_ID',
            hours_ahead = hour_lookahead
        )
        print("\n")

        prevalence = sum(v == 1 for v in targets_dict.values()) / len(targets_dict)
        print(f"\t\t- {format(len(targets_dict), ',')} total key-value pairs in targets_dict.")
        print(f"\t\t\t- Prevalence: {round(100 * prevalence, 2)}%.")

        # remove max order in time window key (there is no subsequent outcome on which to judge its outcome)
        max_order_in_time_window = df[f'{hour_feature_window}_order_in_time_window'].max()
        targets_dict = {
            k: v for k, v in targets_dict.items()
            if int(k[6:9]) != max_order_in_time_window
        }
        prevalence = sum(v == 1 for v in targets_dict.values()) / len(targets_dict)
        print(f"\t\t- {format(len(targets_dict), ',')} total key-value pairs in targets_dict.")
        print(f"\t\t\t- Prevalence: {round(100 * prevalence, 2)}%.")

        # save as JSON
        SAVE_FILENAME = f'targets_dict_anyfailure_{hour_feature_window}hrfeaturewindow_{hour_lookahead}hrlookahead.json'
        SAVE_LOC = os.path.join(SAVE_DATA_DIR, SAVE_FILENAME)
        with open(SAVE_LOC, mode = 'w') as json_f:
          json.dump(obj = targets_dict, fp = json_f, indent = 4)
        print(f"\t\t*Saved file: {SAVE_FILENAME}")

- Hour Feature Window: 12
*Skipping (hour_feature_window, hour_lookahead) = (12, 1)
*Skipping (hour_feature_window, hour_lookahead) = (12, 6)
*Skipping (hour_feature_window, hour_lookahead) = (12, 24)
	- Hours Lookahead: 72
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100

		- 73,100 total key-value pairs in targets_dict.
			- Prevalence: 5.77%.
		- 73,000 total key-value pairs in targets_dict.
			- Prevalence: 5.77%.
		*Saved file: targets_dict_anyfailure_12hrfeaturewindow_72hrlookahead.json
*Skipping (hour_feature_window, hour_lookahead) = (12, 168)
- Hour Feature Window: 24
	- Hours Lookahead: 1
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100

		- 36,600 total key-value pairs in targets_dict.
			- Prevalence: 1.92%.
		- 36,500 total key-value pairs in targets_dict.
			- Prevalence: 1.92%.
		*Saved file: targets_dict_anyfailure_24hrfeaturewindow_1hrlookahead.json
	- Hours Lookahead: 6
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100

		- 36,600 total key-value pairs in targets_dict.
			- Prevalence: 1.92%.
		- 36,500 total key-value pairs in targets_dict.
			- Prevalence: 1.92%.
		*Saved file: targets_dict_anyfailure_24hrfeaturewindow_6hrlookahead.json
	- Hours Lookahead: 24
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100

		- 36,600 total key-value pairs in targets_dict.
			- Prevalence: 1.92%.
		- 36,500 total key-value pairs in targets_dict.
			- Prevalence: 1.92%.
		*Saved file: targets_dict_anyfailure_24hrfeaturewindow_24hrlookahead.json
	- Hours Lookahead: 72
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100

		- 36,600 total key-value pairs in targets_dict.
			- Prevalence: 5.74%.
		- 36,500 total key-value pairs in targets_dict.
			- Prevalence: 5.75%.
		*Saved file: targets_dict_anyfailure_24hrfeaturewindow_72hrlookahead.json
	- Hours Lookahead: 168
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100

		- 36,600 total key-value pairs in targets_dict.
			- Prevalence: 13.29%.
		- 36,500 total key-value pairs in targets_dict.
			- Prevalence: 13.29%.
		*Saved file: targets_dict_anyfailure_24hrfeaturewindow_168hrlookahead.json
- Hour Feature Window: 48
	- Hours Lookahead: 1
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100

		- 18,300 total key-value pairs in targets_dict.
			- Prevalence: 1.94%.
		- 18,200 total key-value pairs in targets_dict.
			- Prevalence: 1.94%.
		*Saved file: targets_dict_anyfailure_48hrfeaturewindow_1hrlookahead.json
	- Hours Lookahead: 6
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100

		- 18,300 total key-value pairs in targets_dict.
			- Prevalence: 1.94%.
		- 18,200 total key-value pairs in targets_dict.
			- Prevalence: 1.94%.
		*Saved file: targets_dict_anyfailure_48hrfeaturewindow_6hrlookahead.json
	- Hours Lookahead: 24
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100

		- 18,300 total key-value pairs in targets_dict.
			- Prevalence: 1.94%.
		- 18,200 total key-value pairs in targets_dict.
			- Prevalence: 1.94%.
		*Saved file: targets_dict_anyfailure_48hrfeaturewindow_24hrlookahead.json
	- Hours Lookahead: 72
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100

		- 18,300 total key-value pairs in targets_dict.
			- Prevalence: 5.76%.
		- 18,200 total key-value pairs in targets_dict.
			- Prevalence: 5.76%.
		*Saved file: targets_dict_anyfailure_48hrfeaturewindow_72hrlookahead.json
	- Hours Lookahead: 168
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100

		- 18,300 total key-value pairs in targets_dict.
			- Prevalence: 13.29%.
		- 18,200 total key-value pairs in targets_dict.
			- Prevalence: 13.32%.
		*Saved file: targets_dict_anyfailure_48hrfeaturewindow_168hrlookahead.json
- Hour Feature Window: 72
	- Hours Lookahead: 1
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100

		- 12,200 total key-value pairs in targets_dict.
			- Prevalence: 2.07%.
		- 12,100 total key-value pairs in targets_dict.
			- Prevalence: 2.08%.
		*Saved file: targets_dict_anyfailure_72hrfeaturewindow_1hrlookahead.json
	- Hours Lookahead: 6
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100

		- 12,200 total key-value pairs in targets_dict.
			- Prevalence: 2.07%.
		- 12,100 total key-value pairs in targets_dict.
			- Prevalence: 2.08%.
		*Saved file: targets_dict_anyfailure_72hrfeaturewindow_6hrlookahead.json
	- Hours Lookahead: 24
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100

		- 12,200 total key-value pairs in targets_dict.
			- Prevalence: 2.07%.
		- 12,100 total key-value pairs in targets_dict.
			- Prevalence: 2.08%.
		*Saved file: targets_dict_anyfailure_72hrfeaturewindow_24hrlookahead.json
	- Hours Lookahead: 72
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100

		- 12,200 total key-value pairs in targets_dict.
			- Prevalence: 5.73%.
		- 12,100 total key-value pairs in targets_dict.
			- Prevalence: 5.74%.
		*Saved file: targets_dict_anyfailure_72hrfeaturewindow_72hrlookahead.json
	- Hours Lookahead: 168
1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100

		- 12,200 total key-value pairs in targets_dict.
			- Prevalence: 13.41%.
		- 12,100 total key-value pairs in targets_dict.
			- Prevalence: 13.45%.
		*Saved file: targets_dict_anyfailure_72hrfeaturewindow_168hrlookahead.json

##### 2.1) Create Targets for 12 Hour Window Features

###### 2.1.1) 12 Hour Window Features, 1 Hour Lookahead

In [33]:
targets_dict = identify_future_failures_dict(
    df = df,
    machine_example_id_col = '12_machine_example_ID',
    hours_ahead = 1
)

prevalence = sum(v == 1 for v in targets_dict.values()) / len(targets_dict)
print(f"- {format(len(targets_dict), ',')} total key-value pairs in targets_dict.")
print(f"\t- Prevalence: {round(100 * prevalence, 2)}%.")

1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   - 73,100 total key-value pairs in targets_dict.
	- Prevalence: 0.96%.

In [34]:
# remove max order in time window key (there is no subsequent outcome on which to judge its outcome)
max_order_in_time_window = df['12_order_in_time_window'].max()
targets_dict = {
    k: v for k, v in targets_dict.items()
    if int(k[6:9]) != max_order_in_time_window
}

prevalence = sum(v == 1 for v in targets_dict.values()) / len(targets_dict)
print(f"- {format(len(targets_dict), ',')} total key-value pairs in targets_dict.")
print(f"\t- Prevalence: {round(100 * prevalence, 2)}%.")

- 73,000 total key-value pairs in targets_dict.
	- Prevalence: 0.96%.

In [35]:
SAVE_FILENAME = 'targets_dict_anyfailure_12hrfeaturewindow_1hrlookahead.json'
SAVE_LOC = os.path.join(SAVE_DATA_DIR, SAVE_FILENAME)

with open(SAVE_LOC, mode = 'w') as json_f:
  json.dump(obj = targets_dict, fp = json_f, indent = 4)

##### 2.2) Create Targets for 24 Hour Window Features

###### 2.2.1) 24 Hour Window Features, 1 Hour Lookahead

In [36]:
targets_dict = identify_future_failures_dict(
    df = df,
    machine_example_id_col = '24_machine_example_ID',
    hours_ahead = 1
)

prevalence = sum(v == 1 for v in targets_dict.values()) / len(targets_dict)
print(f"- {format(len(targets_dict), ',')} total key-value pairs in targets_dict.")
print(f"\t- Prevalence: {round(100 * prevalence, 2)}%.")

1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   - 36,600 total key-value pairs in targets_dict.
	- Prevalence: 1.92%.

###### 2.2.2) 24 Hour Window Features, 6 Hour Lookahead

In [37]:
targets_dict = identify_future_failures_dict(
    df = df,
    machine_example_id_col = '24_machine_example_ID',
    hours_ahead = 6
)

prevalence = sum(v == 1 for v in targets_dict.values()) / len(targets_dict)
print(f"- {format(len(targets_dict), ',')} total key-value pairs in targets_dict.")
print(f"\t- Prevalence: {round(100 * prevalence, 2)}%.")

1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   - 36,600 total key-value pairs in targets_dict.
	- Prevalence: 1.92%.

In [38]:
targets_dict = identify_future_failures_dict(
    df = df,
    machine_example_id_col = '24_machine_example_ID',
    hours_ahead = 24
)

prevalence = sum(v == 1 for v in targets_dict.values()) / len(targets_dict)
print(f"- {format(len(targets_dict), ',')} total key-value pairs in targets_dict.")
print(f"\t- Prevalence: {round(100 * prevalence, 2)}%.")

1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   - 36,600 total key-value pairs in targets_dict.
	- Prevalence: 1.92%.

In [39]:
targets_dict = identify_future_failures_dict(
    df = df,
    machine_example_id_col = '24_machine_example_ID',
    hours_ahead = 96
)

prevalence = sum(v == 1 for v in targets_dict.values()) / len(targets_dict)
print(f"- {format(len(targets_dict), ',')} total key-value pairs in targets_dict.")
print(f"\t- Prevalence: {round(100 * prevalence, 2)}%.")

1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   - 36,600 total key-value pairs in targets_dict.
	- Prevalence: 7.64%.

In [40]:
targets_dict = identify_future_failures_dict(
    df = df,
    machine_example_id_col = '24_machine_example_ID',
    hours_ahead = 168
)

prevalence = sum(v == 1 for v in targets_dict.values()) / len(targets_dict)
print(f"- {format(len(targets_dict), ',')} total key-value pairs in targets_dict.")
print(f"\t- Prevalence: {round(100 * prevalence, 2)}%.")

1   2   3   4   5   6   7   8   9   10   11   12   13   14   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100   - 36,600 total key-value pairs in targets_dict.
	- Prevalence: 13.29%.